BlackBasta ransomware
center-for-threat-informed-defense/attack-flow pull request #127
Opened 2024-07-12 15:41 UTC by lparker31

Added BlackBasta ransomware flow. This will need to be updated if changes are made to the Windows Registry Key STIX observable node. I didn't add the json file because it appeared that only .afb files were in the corpus folder now. If json file is needed, I can provide it.

2024-07-16 18:44 UTC, mehaase commented
A few requested changes:

<img width="588" alt="Screenshot 2024-07-16 at 2 16 28 PM" src="https://github.com/user-attachments/assets/fa74607f-d200-4a1f-bed1-777abc02751f">

Please move the arrows so they don't overlap. There are a few places in the flow where I saw overlapping arrows.

<img width="304" alt="Screenshot 2024-07-16 at 2 18 00 PM" src="https://github.com/user-attachments/assets/494c742e-fe0a-4bff-85eb-4a1c10921d0a">

Correct me if I'm wrong, but I think `IsDebuggerPresent` is a windows API, not a command line tool. (And if it is, we don't have STIX objects for API calls. It could be included in the flow as a note, possibly.)

<img width="471" alt="Screenshot 2024-07-16 at 2 20 11 PM" src="https://github.com/user-attachments/assets/a19752bd-e6c9-48a7-be5a-ad0d46acc908">

This registry key is showing as blank. It should be set up like this:

* Key: `HKEY_CURRENT_USER\Control Panel`
* Value:
    * Name: `Wallpaper`
    * Data: `C:\Temp\dlaksjdoiwq.jpg` (I found this in a [trend micro report](https://www.trendmicro.com/en_us/research/22/e/examining-the-black-basta-ransomwares-infection-routine.html) -- are these randomized for each infection or are these stable within a single campaign?)
    * Data Type: `REG_SZ`

<img width="692" alt="Screenshot 2024-07-16 at 2 29 50 PM" src="https://github.com/user-attachments/assets/7d5bf9ed-d162-4158-bb0d-da99f0a12a94">

I don't think this dependency is accurate, i.e. booting in safe mode does not _depend_ on setting the wallpaper key in the registry, it just happens _after_. The reason why this is important is because we want to look at where we can disrupt attacks. In this case, if we detect or prevent writes to the wallpaper registry key, that doesn't really affect the rest of the attack.

<img width="558" alt="Screenshot 2024-07-16 at 2 31 26 PM" src="https://github.com/user-attachments/assets/6a459988-26ed-47c8-a2bd-498c3daffe2e">

File isn't the right object to use here, because `.basta` isn't a single specific file. You could _maybe_ use an Indicator object and set the pattern using the [STIX Patterns language](https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_e8slinrhxcc9:~:text=13T07%3A03%3A17Z%27-,9.3%20STIX%20Patterns,-STIX%20Patterns%20are). But that seems overkill. I suggest removing the File object here.

<img width="638" alt="Screenshot 2024-07-16 at 2 35 11 PM" src="https://github.com/user-attachments/assets/4e5c13ef-57d2-4f2b-8834-60e77621950e">

Same thing here. The File object is meant to be used as an indicator, i.e. "go search your network for this file name." But I don't think basta is making a file called `random-letters.ico`, it's actually making files like `fdsjskjsfak.ico`. If this filename is stable across multiple incidents, then it's worth including as an indicator, otherwise let's just explain in the action description that it's creating random file names.

<img width="642" alt="Screenshot 2024-07-16 at 2 38 25 PM" src="https://github.com/user-attachments/assets/cc49cd5e-141b-4234-b8df-387a7457e5de">

T1657 should be moved earlier in the flow, e.g. an offshot of the exfiltration action, because it does not depend on the encryption for impact leg of the flow.

2024-07-16 18:44 UTC, mehaase requested changes
Requested a few changes. See comment above.

2024-08-15 14:01 UTC, lparker31 commented
Fixed flow based on recommended changes.

2024-08-21 18:39 UTC, mehaase approved these changes

2024-08-21 18:39 UTC, merged