Publish quality attack flow diagrams.
center-for-threat-informed-defense/attack-flow pull request #43
Opened 2022-05-17 22:29 UTC by curious-attempt-bunny

Fixes #42 

## What Changed

1. Tidied up graphviz script output. Now it aligns better with the style of the manually created drawio diagrams.

### Before

![image](https://user-images.githubusercontent.com/51608/168922619-cf4bc617-cf6f-4415-9544-da594b480db5.png)

### After

![image](https://user-images.githubusercontent.com/51608/168922546-338e6ab1-d578-4398-9f84-34f563c73941.png)

## Limitations

1. None

2022-05-18 12:43 UTC, mehaase requested changes
Thanks for making this PR. The output looks great. I have one comment on the diff, and can you also please fix the [build errors](https://github.com/center-for-threat-informed-defense/attack-flow/runs/6489201008?check_suite_focus=true)? The build is failing because:

1. The graphviz test needs to be updated (run the test suite locally with `pytest --cov=src/ --cov-report term-missing`)
2. Some flake8 formatting issues, mainly long lines (>120 chars) in graphviz.py. I suggest unrolling some of the list comprehensions but I'll leave that up to you.

2022-05-18 12:43 UTC, mehaase commented on src/attack_flow/graphviz.py
> +def align_node_label(label: str, width=20) -> str:
Can you add a docstring to this method that explains what it does?

2022-05-19 23:19 UTC, curious-attempt-bunny commented
@mehaase I addressed the feedback. Although somehow there are now 116 Security Hotspots according to SonarCloud - but I'm unable to view the report.

I also added documentation for running the tests, added the flake checks to the makefile, duplicated the flake8 configuration so that it's picked up out of the box by the MS Visual Studio plugin, and

2022-05-20 12:26 UTC, mehaase requested changes

2022-05-20 12:26 UTC, mehaase commented on src/attack_flow/graphviz.py
> +GRAPHVIZ_NODE_STYLE_COMMON = ''
Is this used anywhere? If not, please delete.

2022-05-20 12:26 UTC, mehaase commented on src/attack_flow/graphviz.py
> +                labelText = "provides"
Change to `label_text`.

2022-05-20 15:51 UTC, curious-attempt-bunny commented
@mehasse Cleaned up. Thanks for your time reviewing these changes.

2022-05-20 16:19 UTC, mehaase approved these changes

2022-05-20 16:19 UTC, merged

2022-05-20 16:20 UTC, mehaase commented
Thank you for the contribution @curious-attempt-bunny! This will definitely be valuable to the community at large.